spring:
  application:
    name: discovery-server

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false

  dashboard:
    enabled: true
